### ISSUE TITLE
About checking problem

### ISSUE THREAD

**Issue by qzwlecr** [FluorineDog/uniquelab-2017-summer-assignment-1#1]
In set and priority_queue interface, we can't access the data and can't check the correctness. Maybe.

**Comment by kylerky** [comment]
@qzwlecr priority_queue is ok. But we need some methods to read the data in set.

**Comment by qzwlecr** [comment]
Also, please add unit test to the assignment.

**Comment by kylerky** [comment]
@qzwlecr count can help us test the validity. 
see [std::set::count](http://en.cppreference.com/w/cpp/container/set/count)

**Comment by FluorineDog** [comment]
Feel free to add more methods, but current API shall be enough for now.

**Comment by FluorineDog** [comment]
Unit tests will be available "soon".

**Comment by viseator** [comment]
Why you guys speaking English now?

**Comment by klx3300** [comment]
chinese ime exploded(

**Comment by FluorineDog** [comment]
As for Chinese locale, GB2312 or UTF-8 is a hard choice, even for Intel :(
shiyongpinyinyouhenchun
So make English great again! // Chinglish or Trumpese in fact:(
